[package]
authors = ["Alex Whitney <adwhit@fastmail.com>"]
name = "openapi3"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
regex = "0.2.2"
serde_derive = "1.0.10"
serde_yaml = "0.7.1"

[dependencies.serde]
features = ["rc"]
version = "1.0.10"
