[package]
authors = ["Alex Whitney <adwhit@fastmail.com>"]
name = "openapi3"
version = "0.1.0"

[dependencies]
derive-new = "0.5"
error-chain = "0.10"
regex = "0.2"
serde_derive = "1"
serde_yaml = "0.7"

[dependencies.serde]
features = ["rc"]
version = "1"
