[package]
authors = ["Alex Whitney <adwhit@fastmail.com>"]
name = "openapi3"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"
serde_yaml = "0.7.1"
